Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls")),
    path("", include("business.urls")),
]

users/urls.py
from django.urls import path
from . import views
urlpatterns = [
  path("register/", view=views.register, name="register"),
  path("modifyAccount/", views.modify_user, name="modifyAccount"),
]

business/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields.files import ImageField

ORDER_STATUS = (
  ("NEW", "NEW"),
  ("ACCEPTED", "ACCEPTED"),
  ("CANCELED", "CANCELED"),
  ("DELIVERING", "DELIVERING"),
  ("COMPLETED", "COMPLETED"),
)

SIZE = (
  ("M", "M"),
  ("L", "L"),
  ("XL", "XL"),
)

PAYMENT_METHOD = (
  ("ON DELIVER", "ON DELIVER"),
  ("BANKING", "BANKING"),
)

class Shop(models.Model):
  name = models.CharField(max_length=100)
  phone = models.CharField(max_length=20)
  mail = models.CharField(max_length=100)
  des = models.CharField(max_length=500)
  def __str__(self):
    return f"Shop {self.name}"

class Staff(models.Model):
  user = models.OneToOneField(User, related_name="staff_info", on_delete=models.CASCADE)
  staff_position = models.CharField(max_length=100)
  def __str__(self):
    return f"Staff {self.user}"

class Customer(models.Model):
  user = models.OneToOneField(User, related_name="customer_info", on_delete=models.CASCADE)
  phone = models.CharField(max_length=15, blank=True, null=True)
  def __str__(self):
    return f"Customer {self.user}"

class Address(models.Model):
  address_type = models.CharField(max_length=100)
  apartment_number = models.CharField(max_length=100, null=True)
  street = models.CharField(max_length=100, null=True)
  distric = models.CharField(max_length=100, null=True)
  city_or_province = models.CharField(max_length=100, null=True)
  phone = models.CharField(max_length=15, null=True)
  customer = models.ForeignKey(Customer, related_name="address", on_delete=models.CASCADE)
  def __str__(self):
    return f"{self.customer} {self.address_type}"
  @property
  def get_detailed_address(self):
    return f"{self.apartment_number}, {self.street}, {self.distric}, {self.city_or_province}"

class Category(models.Model):
  name = models.CharField(max_length=100)
  def __str__(self):
    return self.name

class SubCategory(models.Model):
  name = models.CharField(max_length=100)
  category = models.ForeignKey(Category, related_name="sub_categorys", on_delete=models.CASCADE)
  def __str__(self):
    return f"{self.category} {self.name}"

class Item(models.Model):
  name = models.CharField(max_length=100)
  brand = models.CharField(max_length=50)
  cost = models.FloatField() 
  remaining_quantity = models.PositiveIntegerField()
  des = models.TextField()
  category = models.ForeignKey(Category, related_name="category_items", on_delete=models.CASCADE)
  image = models.ImageField(null=True)
  def __str__(self):
    return f"Item {self.name}"

class Book(models.Model):
  item = models.OneToOneField(Item, on_delete=models.CASCADE, related_name="book")
  author = models.CharField(max_length=100)
  publishing_company = models.CharField(max_length=100)
  publishcation_date = models.DateField()
  number_of_page = models.PositiveIntegerField()
  sub_category = models.ManyToManyField(SubCategory, related_name="book_sub_category")
  def __str__(self):
    return f"Book item - {self.item}"
  @property
  def get_book_sub_category(self):
    return ",".join([s.name for s in self.sub_category.all()])

class Clothes(models.Model):
  item = models.OneToOneField(Item, on_delete=models.CASCADE, related_name="clothes")
  material = models.CharField(max_length=200)
  size = models.CharField(choices=SIZE, max_length=5, null=True, blank=True)
  sub_category = models.ForeignKey(SubCategory, related_name="clothes_sub_category", on_delete=models.CASCADE)
  def __str__(self):
    return f"Clothes item - {self.item}"

class ClothesDetail(models.Model):
  color = models.CharField(max_length=20)
  image = models.ImageField()
  clothes = models.ForeignKey(Clothes, related_name="details", on_delete=models.CASCADE)
  def __str__(self):
    return f"{self.clothes} {self.color}"

class Electric(models.Model):
  item = models.OneToOneField(Item, on_delete=models.CASCADE, related_name="electric")
  guarantee = models.IntegerField()
  sub_category = models.ForeignKey(SubCategory, related_name="electric_sub_category", on_delete=models.CASCADE)
  def __str__(self):
    return f"Electric item - {self.item}"

class Cart(models.Model):
  customer = models.ForeignKey(Customer, related_name="cart", on_delete=models.CASCADE)
  def __str__(self):
    return f"Cart - {self.customer}"

class Order(models.Model):
  customer = models.ForeignKey(Customer, related_name="order", on_delete=models.CASCADE)
  order_time = models.DateTimeField(auto_now_add=True)
  order_status = models.CharField(choices=ORDER_STATUS, default="NEW", max_length=10)
  total = models.FloatField()
  def __str__(self):
    return f"Order - {self.customer}"

class Shipment(models.Model):
  order = models.OneToOneField(Order, related_name="shipment", on_delete=models.CASCADE)
  ship_provider = models.CharField(max_length=100)
  ship_fee = models.FloatField()
  pickup_date = models.DateField(blank=True, null=True)
  expected_ship_date = models.DateField(blank=True, null=True)
  ship_address = models.ForeignKey(Address, on_delete=models.CASCADE, null=True)
  def __str__(self):
    return f"Shipment - {self.order}"

class Payment(models.Model):
  order = models.OneToOneField(Order, related_name="payment", on_delete=models.CASCADE)
  payment_method = models.CharField(choices=PAYMENT_METHOD, default="ON DELIVER", max_length=10)
  total_pay = models.FloatField()
  def __str__(self):
    return f"Payment - {self.order}"

class CartItem(models.Model):
  item = models.ForeignKey(Item, on_delete=models.CASCADE)
  quantity = models.PositiveIntegerField()
  cart = models.ForeignKey(Cart, related_name="bookItems", on_delete=models.CASCADE)
  order = models.ForeignKey(Order, related_name="orderItems", on_delete=models.CASCADE, blank=True, null=True)
  def __str__(self):
    return f"Cart item - {self.order} - {self.item}"

class Review(models.Model):
  star = models.PositiveIntegerField()
  content = models.CharField(max_length=200)
  created_time = models.DateTimeField(auto_now_add=True)
  item = models.ForeignKey(Item, related_name="item_reviews", on_delete=models.CASCADE)
  customer = models.ForeignKey(Customer, related_name="customer_reviews", on_delete=models.CASCADE)
  def __str__(self):
    return f"Review - {self.customer} - {self.item} - {self.created_time} "

class ShopFeedback(models.Model):
  review = models.ForeignKey(Review, related_name="shop_feedback", on_delete=models.CASCADE)
  content = models.CharField(max_length=200)
  created_time = models.DateTimeField(auto_now_add=True)
  def __str__(self):
    return f"Shop feedback - {self.review}"
  
class Message(models.Model):
  staff = models.ForeignKey(Staff, related_name="sent_messages", on_delete=models.CASCADE)
  customer = models.ForeignKey(Customer, related_name="sent_messages", on_delete=models.CASCADE)
  content = models.CharField(max_length=300)
  created_time = models.DateTimeField(auto_now_add=True)
  def __str__(self):
    return f"Message - {self.staff} - {self.customer} - {self.created_time}"

class Voucher(models.Model):
  value = models.FloatField()
  expired = models.DateField()
  code = models.CharField(max_length=10)
  def __str__(self):
    return f"Voucher - {self.code} - {self.value}"
 
class ProductVoucher(Voucher):
  item = models.ForeignKey(Item, related_name="item_vouchers", on_delete=models.CASCADE)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

class CustomUserCreationForm(UserCreationForm):
  phone = forms.CharField()

class CustomUserCreationForm2(UserCreationForm):
  phone = forms.CharField()
  class Meta(UserCreationForm.Meta):
    fields = UserCreationForm.Meta.fields + ("email", "first_name", "last_name",)

templates/account.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block title %}
  Account
{% endblock %}

{% block css %}
  <style>
    table, tr, td {
      padding: 5px;
    }
    input {
      padding: 3px 5px;
    }
  </style>  
{% endblock %}

{% block content %}
<div class="container">
  <div class="row my-3">
    <div class="col-6">
      <h3>My account</h3>
      <div class="account-info">
        <form action="{% url 'modifyAccount' %}" method="POST">
          {% csrf_token %}
          <table>
            <tbody>
              <tr>
                <td><label for="id_username">Username</label></td>
                <td><input type="text" name="username" id="id_username" value="{{ user.username }}" size="30" data-row="1" disabled></td>
                <!-- <td><button class="btn btn-primary edit-btn" data-row="1" type="button"><i class="fa fab fa-edit"></i></button></td> -->
              </tr>
              <tr>
                <td><label for="id_first_name">First name</label></td>
                <td><input type="text" name="first_name" id="id_first_name" value="{{ user.first_name }}" size="30" data-row="2" disabled></td>
                <!-- <td><button class="btn btn-primary edit-btn" data-row="2" type="button"><i class="fa fab fa-edit"></i></button></td> -->
              </tr>
              <tr>
                <td><label for="id_last_name">Last name</label></td>
                <td><input type="text" name="last_name" id="id_last_name" value="{{ user.last_name }}" size="30" data-row="3" disabled></td>
                <!-- <td><button class="btn btn-primary edit-btn" data-row="3" type="button"><i class="fa fab fa-edit"></i></button></td> -->
              </tr>
              <tr>
                <td><label for="id_email">Email</label></td>
                <td><input type="text" name="email" id="id_email" value="{{ user.email }}" size="30" data-row="4" disabled></td>
                <!-- <td><button class="btn btn-primary edit-btn" data-row="4" type="button"><i class="fa fab fa-edit"></i></button></td> -->
              </tr>
            </tbody>
          </table>
          <!-- <div class="form-action d-none">
            <button class="btn btn-info">Save</button>
            <button class="btn btn-danger" type="button" id="cancel-btn">Cancel</button>
          </div> -->
        </form>
      </div>
    </div>
    {% if not user.is_staff %}
    <div class="col-6">
      <h3>Customer</h3>
      <table>
        <tr>
          <td><label for="phone">Phone</label></td>
          <td><input type="text" name="phone" value="{{ customer.phone }}"></td>
        </tr>
      </table>
      <table>
        <h4>Address</h4>
        {% for address in customer.address.all %}
        <tr>
          <td>Address{{ forloop.counter }}</td>
          <td>{{ address.get_detailed_address }}</td>
        </tr>
        {% empty %}
        <div>No address</div>
        {% endfor %}
        <button class="btn btn-info btn-add-address">Add</button>
      </table>
      <form action="{% url 'customerAddress' %}" method="POST" id="address-form" class="d-none">
        {% csrf_token %}
        <table>
          <tr>
            <td><label for="id_address_type">Address type</label></td>
            <td>{{ form.address_type }}</td>
          </tr>
          <tr>
            <td><label for="id_apartment_number"> Apartment number</label></td>
            <td>{{ form.apartment_number }}</td>
          </tr>
          <tr>
            <td><label for="id_street">Street</label></td>
            <td>{{ form.street }}</td>
          </tr>
          <tr>
            <td><label for="id_distric">District</label></td>
            <td>{{ form.distric }}</td>
          </tr>
          <tr>
            <td><label for="id_city_or_province">City/Province</label></td>
            <td>{{ form.city_or_province }}</td>
          </tr>
          <tr>
            <td><label for="id_phone">Phone</label></td>
            <td>{{ form.phone }}</td>
          </tr>
        </table>
        <input type="hidden" name="addresspk" value="{{ address.pk }}">
        <input type="hidden" name="customerpk" value="{{ customer.pk }}">
        <button class="btn btn-info">Save</button>
        <button class="btn btn-danger" type="button" id="cancel-btn2">Cancel</button>
      </form>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

{% block js %}
<script>
  $("#nav-account").addClass("active");
  // $(".edit-btn").each(function() {
  //   $(this).click(function() {
  //     let row = $(this).data("row");
  //     $("input").each(function() {
  //       if ($(this).data("row") == row) {
  //         $(this).removeAttr("disabled");
  //         $(this).addClass("pending");
  //       }
  //     });
  //     $(".form-action").removeClass("d-none");
  //   });
  // });
  // $("#cancel-btn").click(function() {
  //   $(".form-action").addClass("d-none");
  //   $("input.pending").each(function() {  
  //     $(this).attr("disabled", true);
  //   });
  // });

  $(".btn-add-address").click(function(){
    $("#address-form").removeClass("d-none");
  });
  $("#cancel-btn2").click(function () {
    $("#address-form").addClass("d-none");
  });
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    {% endblock %}
  </title>
  {% load static %}
  {% load humanize %}
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'fontawesome-free-5.13.0-web/css/all.min.css' %}">
  {% block css %}
  {% endblock %}
</head>
<body>
  <!-- header -->
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">Shopping</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="nav-cart" href="{% url 'cart' %}">Cart</a>
          <a class="nav-item nav-link" id="nav-order" href="{% url 'orderView' %}">Order</a>
          {% if request.user.is_staff %}
          <a class="nav-item nav-link" id="nav-staff" href="{% url 'staff_home' %}">Staff Function</a>
          {% endif %}
        </div>
        <div class="navbar-nav ml-auto">
          <form class="form-inline my-2 my-lg-0 mx-2" action="{% url 'search' %}" method="GET">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" name="search_data" aria-label="Search" value="{{ search_data }}">
            <button class="btn btn-outline-light my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
          </form>
          {% if user.is_anonymous %}
          <a class="nav-item nav-link nav-user">Hello, Anonymous user</a>
          <a class="nav-item nav-link nav-func" href="{% url 'login'%}">Login</a>
          {% elif not user.is_anonymous %}
          <a class="nav-item nav-link nav-user" id="nav-account" href="{% url 'myAccount' %}">Hello, {{ user }}</a>
          {% endif %}
          {% if not user.is_anonymous and not user.is_staff %}
          <a class="nav-item nav-link nav-noti" href="{% url 'notification' %}">Notificaton</a>
          {% endif %}
          {% if not user.is_anonymous%}
          <a class="nav-item nav-link nav-func" href="{% url 'logout'%}">Logout</a>
          {% endif %}
        </div>
      </div>
    </nav>
  </header>

  <main class="">
    {% block content %}
    {% endblock %}
  </main>

  <!-- footer -->
  <!-- <footer>
    copyright@2021
  </footer> -->

  <script src="{% static 'jquery/jquery.min.js' %}" ></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <!-- myscript -->
  {% block js %}
  {% endblock %}
</body>
</html>

templates/feedback.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block title %}
  Notification
{% endblock %}

{% block css %}
  <style>
    .star {
      font-size: 20px;
    }

    .rated {
      color: orange;
    }

    .rating {
      counter-reset: rate_value 0;
    }

    .star.ustar.rated {
      counter-increment: rate_value 1;
    }

    .rating::after {
      margin-top: 20px;
      display: block;
      content: "Đánh giá " counter(rate_value) "/5";
    }

    .form-control {
      width: 100%;
    }

    .review-form {
      display: grid;
      grid-template-columns: 1fr 2fr;
      column-gap: 20px;
    }

    .review-container {
      margin-bottom: 20px;
    }

    .user-comment {
      padding: 5px 10px;
    }

    .user-comment-rated {
      margin: auto 10px;
      color: #393e46;
      font-weight: lighter;
    }

    .comment {
      margin-left: 15px;
    }

    .feedback-item {
      border: #393e46 1px solid;
    }

  </style>  
{% endblock %}

{% block content %}
<div class="container">
  {% for review in reviews %}
  {% if not review.shop_feedback.all %}
  <div class="feedback-item row mb-2 p-2">
    <div class="col-4">
      <img src="{{ review.item.image.url }}" class="card-img-top" alt="..." height="200px">
      <p> {{ review.item.name }} </p>
    </div>
    <div class="col-8">
      <div class="user-comment">
        <h5 class="username head">
          <span><i class="fa fa-user"></i></span> 
          {{ review.customer.user }} 
          <span class="user-comment-rated"> đã đánh giá </span> 
          {% for i in dstars %}
            {% if i <= review.star %}
              <span class="star rated">★</span>
            {% else %}
              <span class="star">★</span>
            {% endif %}
          {% endfor %}
        </h4>
        <p class="comment"><span><i class="fa fa-comment"></i></span> {{review.content}}</p>
      </div>
      <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="review_id" value="{{ review.pk }}">
        <textarea name="content" rows="3" class="form-control">{{ review.shop_feedback.all.0.content }}</textarea>
        <button class="btn btn-primary mt-2">Send</button>
      </form>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
{% endblock %}

{% block js %}
<script>
  $(".nav-noti").addClass("active");
</script>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}
  Home
{% endblock %}

{% load humanize %}

{% block css %}
  <style>
    .panel {
      padding: 3% 5% !important;
    }
    .items {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      
    }

    a.card-title {
      color: black;
    }
    .card {
      /* Add shadows to create the "card" effect */
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.5);
      transition: 0.3s;
    }

    /* On mouse-over, add a deeper shadow */
    .card:hover {
      box-shadow: 0 8px 16px 0 rgba(0,0,0,0.7);
    }

  </style>
{% endblock %}

{% block content %}
  <div class="panel books-panel p-4">
    <h4 class="">Sách</h4>
    <div class="items">
    {% for book in books %}
      <div class="card m-2" style="width: 16rem;">
        <img src="{{ book.item.image.url }}" class="card-img-top" alt="..." height="150px">
        <div class="card-body bg-dark text-light">
          <h5><a class="text-light" href="{% url 'item' book.item.pk %}">{{ book.item.name }}</a></h5>
          <p class="card-text">{{ book.item.cost|floatformat:0|intcomma }} VND</p>
        </div>
      </div>
    {% endfor %}
    </div>  
  </div>
  <div class="panel clothes-panel bg-dark text-light">
    <h4 class="">Quần áo</h4>
    <div class="items">
    {% for cloth in clothes %}
      <div class="card m-2" style="width: 16rem;">
        <img src="{{ cloth.item.image.url }}" class="card-img-top" alt="..." height="150px">
        <div class="card-body text-dark">
          <h5><a class="text-dark" href="{% url 'item' cloth.item.pk %}">{{ cloth.item.name }}</a></h5>
          <p class="card-text">{{ cloth.item.cost|floatformat:0|intcomma }} VND</p>
        </div>
      </div>
    {% endfor %}
    </div>  
  </div>
  <div class="panel electrics-panel">
    <h4 class="">Đồ điện tử</h4>
    <div class="items">
    {% for electric in electrics %}
      <div class="card m-2" style="width: 16rem;">
        <img src="{{ electric.item.image.url }}" class="card-img-top" alt="..." height="150px">
        <div class="card-body bg-dark text-light">
          <h5><a class="text-light" href="{% url 'item' electric.item.pk %}">{{ electric.item.name }}</a></h5>
          <p class="card-text">{{ electric.item.cost|floatformat:0|intcomma }} VND</p>
        </div>
      </div>
    {% endfor %}
    </div>  
  </div>

{% endblock %}

templates/notification.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block title %}
  Notification
{% endblock %}

{% block css %}
  <style>
    table, tr, td {
      padding: 5px;
    }
    input {
      padding: 3px 5px;
    }
  </style>  
{% endblock %}

{% block content %}
<div class="container">
  {% for message in messages %}
    <p>{{ message.content }}</p>
  {% endfor %}
</div>
{% endblock %}

{% block js %}
<script>
  $(".nav-noti").addClass("active");
</script>
{% endblock %}

templates/order.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block title %}
  Order
{% endblock %}

{% block css %}
  <style>
    hr {
      color: #243f3f;
      border: none;
      border-top: dotted 7px;
      width: 5%;
      margin: 70px auto;
    }
    .order-info {
      text-align: center;
    }

    .nav-user, .nav-func {
      align-self: flex-end;
    }
  </style>  
{% endblock %}

{% block content %}
<div class="container mt-3">
{% for orderItem in orderItems %}
<div class="order-item">
  <div class="order-info bg-dark text-light row pt-2">
    <p class="col-6">Order time: {{ orderItem.order.order_time }}</p>
    <p class="col-6">Status: {{ orderItem.order.get_order_status_display }}</p>
  </div>
  <div class="cart-items">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Product Name</th>
          <th scope="col">Cost (VND)</th>
          <th scope="col">Quantity</th>
          <th scope="col">To (VND)</th>
        </tr>
      </thead>
      <tbody>
        {% load mathfilters %}
        {% for cartItem in orderItem.cartItems %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td style="width: 40rem;">{{ cartItem.item.name }}</td>
          <td>{{ cartItem.item.cost|floatformat:0|intcomma }}</td>
          <td>{{ cartItem.quantity }}</td>
          <td class="item-price" data-amount="{{ cartItem.item.cost|mul:cartItem.quantity }}">{{ cartItem.item.cost|mul:cartItem.quantity|floatformat:0|intcomma }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="ship-info row">
    <div class="col-8">
      <p>Ship provider: {{ orderItem.order.shipment.ship_provider }}</p>
      <p>Ship address: {{ orderItem.order.shipment.ship_address.get_detailed_address }}</p>
      <p>Phone: {{ orderItem.order.shipment.ship_address.phone }}</p>
    </div>
    <div class="col-4 d-flex" style="flex-direction: column; align-items: flex-end;">
      <p>Ship fee: {{ orderItem.order.shipment.ship_fee|floatformat:0|intcomma }} VND</p>
      <p>Total: {{ orderItem.order.total|floatformat:0|intcomma }} VND</p>
    </div>
  </div>
</div>
<hr class="mt-4 mb-4">
{% empty %}
  No ordered item yet.
{% endfor %}
</div>
{% endblock %}

{% block js %}
<script>
  $("#nav-order").addClass("active");
</script>
{% endblock %}

templates/order_detail.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block title %}
  Order
{% endblock %}

{% block css %}
  <style>
    hr {
      color: #243f3f;
      border: none;
      border-top: dotted 7px;
      width: 5%;
      margin: 70px auto;
    }
    .order-info {
      text-align: center;
    }

    .nav-user, .nav-func {
      align-self: flex-end;
    }
  </style>  
{% endblock %}

{% block content %}
<div class="container mt-3">
<div class="order-item">
  <div class="order-info bg-dark text-light row pt-2">
    <p class="col-4">Order code: OD{{ order.pk }}</p>
    <p class="col-4">Order time: {{ order.order_time }}</p>
    <p class="col-4">Status: {{ order.get_order_status_display }}</p>
  </div>
  <div class="cart-items">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Product Name</th>
          <th scope="col">Cost (VND)</th>
          <th scope="col">Quantity</th>
          <th scope="col">To (VND)</th>
        </tr>
      </thead>
      <tbody>
        {% load mathfilters %}
        {% for cartItem in cartItems %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td style="width: 40rem;">{{ cartItem.item.name }}</td>
          <td>{{ cartItem.item.cost|floatformat:0|intcomma }}</td>
          <td>{{ cartItem.quantity }}</td>
          <td class="item-price" data-amount="{{ cartItem.item.cost|mul:cartItem.quantity }}">{{ cartItem.item.cost|mul:cartItem.quantity|floatformat:0|intcomma }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="ship-info row">
    <div class="col-8">
      <p>Ship provider: {{ order.shipment.ship_provider }}</p>
      <p>Customer: {{ order.customer.user }} </p>
      <p>Ship address: {{ order.shipment.ship_address.get_detailed_address }}</p>
      <p>Phone: {{ order.shipment.ship_address.phone }}</p>
    </div>
    <div class="col-4 d-flex" style="flex-direction: column; align-items: flex-end;">
      <p>Ship fee: {{ order.shipment.ship_fee|floatformat:0|intcomma }} VND</p>
      <p>Total: {{ order.total|floatformat:0|intcomma }} VND</p>
    </div>
  </div>
  {% with status=order.order_status %}
  <form action="{% url 'order_management' 'status'%}" method="post" class="mt-2">
    {% csrf_token %}
    <input type="hidden" name="order_id" value=" {{ order.pk }} ">
    {% if status == "NEW" %}
    <input type="hidden" name="order_status" value="ACCEPTED">
    <button class="btn btn-success m-1">Chấp nhận đơn hàng</button>
    {% elif status == "ACCEPTED"%}
    <input type="hidden" name="order_status" value="DELIVERING">
    <button class="btn btn-success m-1">Vận chuyển đơn hàng</button>
    {% elif status == "DELIVERING" %}
    <input type="hidden" name="order_status" value="COMPLETED">
    <button class="btn btn-success m-1">Hoàn thành đơn hàng</button>
    {% endif %}
    {% endwith %}
  </form>
</div>
</div>
{% endblock %}

{% block js %}
<script>
  $("#nav-order").addClass("active");
</script>
{% endblock %}